### ISSUE TITLE
Preprocess doesn't create .npy file

### ISSUE THREAD

**Issue by ks7585** [ChiWeiHsiao/DeepVO_PyTorch#1]
Hi, 

I followed the instructions provided in the readme file.  I noticed that the shell also removed the 03 images (00,01,02,04,....).
On running the preprocess.py. I couldn't get any .npy file saved.

**Comment by ChiWeiHsiao** [comment]
Hi,
Maybe you can check if your ground truth data (00.txt...) is saved in the same location specified in params.py file ( the default is 'KITTI/pose_GT/'. )

**Comment by ChiWeiHsiao** [comment]
Hi,
Maybe you can check if your ground truth data (00.txt...) is saved in the same directory specified in params.py file ( the default is 'KITTI/pose_GT/'. )

**Comment by ChiWeiHsiao** [comment]
Hi,
Could you show what do the program print? And which operating system do you use?

**Comment by ks7585** [comment]
Hi, 
I use Ubuntu OS. I attached the screenshots of the output 
![screenshot from 2018-07-30 15-35-23](https://user-images.githubusercontent.com/33239665/43419370-b3504c32-940e-11e8-9e7d-837aee5f42a2.png)

this is the folder where the .npy files are supposed to be saved. which didn't happen though
![screenshot from 2018-07-30 15-36-17](https://user-images.githubusercontent.com/33239665/43419406-c7b953bc-940e-11e8-8c11-2f3bf5d638fb.png)

**Comment by ChiWeiHsiao** [comment]
Hi,
I have fixed the problem. 
I used split '.' to change extension from .txt to .npy, but this method failed with file paths start with '.')
Hope the new code will work for you :)
