### ISSUE TITLE
how to draw the picture?

### ISSUE THREAD

**Issue by yxh1993** [ChiWeiHsiao/DeepVO_PyTorch#16]

**Comment by yxh1993** [comment]
Hi,how to make the picture by matplotlib?

**Comment by gaiaml** [comment]
Hello,
After the training step you have to :
1) start the **test.py** file
2) start the **visualize.py** file

It will creates a folder called "results" and you will see the trajectory for each path.

You can also configure which data you want to use, just update the **videos_to_test variable** in **test.py** and **video_list** in **visualize**.py

**Comment by yxh1993** [comment]
> Hello,
> After the training step you have to :
> 
> 1. start the **test.py** file
> 2. start the **visualize.py** file
> 
> It will creates a folder called "results" and you will see the trajectory for each path.
> 
> You can also configure which data you want to use, just update the **videos_to_test variable** in **test.py** and **video_list** in **visualize**.py

why i got the result for 04 video like this? /home/yxh/Pictures/Figure_1.png

**Comment by gaiaml** [comment]
We can't see your result.
You need to provide more information. Did you use the pretained weights available on the depot?

**Comment by yxh1993** [comment]
this is my result






At 2019-04-10 16:25:43, "damnedx" <notifications@github.com> wrote:


We can't see your result.
You need to provide more information. Did you use the pretained weights available on the depot?

**Comment by yxh1993** [comment]
> We can't see your result.
> You need to provide more information. Did you use the pretained weights available on the depot?
