### ISSUE TITLE
Large time per iteration / slow computation

### ISSUE THREAD

**Issue by DexterFixxor** [ChiWeiHsiao/DeepVO_PyTorch#26]
Hello, can you tell me how long does your training takes per epoch with raw code from repo, without changing crucial parts? Because for me, it is running a long time, 2 hours per epoch, or something like that. I have imported pretrained **FlowNet** from the link in description, and set **num_workers=0** because of the error I get when I set them to any number higher than zero. 
What are possible ways of improving training speed, for this code in particular?
I am trying to learn as much as I can about Deep Learning, and this repo is going to help me a lot in my study field (robotics). 

Edit: 
I just tested few things, it seems that **get_loss()**, **and step()** function in general, take relativly long time to compute. Is that the case for you too? 
With **batch_size = 8**, **n_workers = 8** I get like 10-12sec per iteration and I even resized images to very small resolution.
Any ides on what is going on?

**Comment by DexterFixxor** [comment]
I just tested few things, it seems that get_loss(), and step() function generaly, take relativly long time to compute. Is that the case for you too? 
With batch_size = 8, n_workers = 8 I get like 10secs per iteration and I even resized images to very small resolution.
Please someone help.

**Comment by GarethZhang** [comment]
I tried on 1 1080Ti and each epoch takes 6 min including training and validating... Is it supposed to be this slow?

**Comment by la735681253** [comment]
> I tried on 1 1080Ti and each epoch takes 6 min including training and validating... Is it supposed to be this slow?

when i run test.py, it show that:
RuntimeError: CUDA out of memory. Tried to allocate 468.75 MiB (GPU 0; 4.00 GiB total capacity; 2.58 GiB already allocated; 2.12 MiB free; 392.23 MiB cached)

can you help me how to solve this problem？ thank you

**Comment by DexterFixxor** [comment]
@la735681253 One way to resolve that problem is to reduce number of workers (n_processors) in parameters. This number determines number of samples to be processed in parallel. Reducing this number will slow down trianing process.

**Comment by la735681253** [comment]
> @la735681253 One way to resolve that problem is to reduce number of workers (n_processors) in parameters. This number determines number of samples to be processed in parallel. Reducing this number will slow down trianing process.

thank you very much ，but i try to reduce n_processors，i also meet the same problem：
Load model from:  models/t000102050809_v04060710_im184x608_s5x7_b8_rnn1000_optAdagrad_lr0.0005.model.train
seq_len = 6,  overlap = 5
Folder 04 finish in 0.016396045684814453 sec
Traceback (most recent call last):
  File "test.py", line 71, in <module>
    batch_predict_pose = M_deepvo.forward(x)
  File "F:\DeepVO-pytorch-master\model.py", line 96, in forward
    out, hc = self.rnn(x)
  File "D:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda\lib\site-packages\torch\nn\modules\rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 516.38 MiB (GPU 0; 4.00 GiB total capacity; 1.97 GiB already allocated; 472.87 MiB free; 544.60 MiB cached)
