### ISSUE TITLE
FlowNet link cracked

### ISSUE THREAD

**Issue by xutong05** [ChiWeiHsiao/DeepVO_PyTorch#47]
The link for pretrained weight of FlowNet ( CNN part ) have been cracked, could you please share the file?

**Comment by venky4121994** [comment]
Here is the link, hope it helps:
https://drive.google.com/drive/folders/1dTpSyc7rIYYG19p1uiDfilcsmSPNy-_3

**Comment by hiXiaoYU** [comment]
@VincentAC-stack @venky4121994 
The file about pretrained weight of FlowNet ( CNN part ) for this download link is corrupted, could you please share the file?
